# Generated by Django 4.1.1 on 2022-09-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
