# Generated by Django 4.1.1 on 2022-09-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mchath', '0002_alter_customer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='op1',
            new_name='Op1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='op2',
            new_name='Op2',
        ),
    ]
